import { test, expect } from '@playwright/test';
import { GeneratorPage } from '../pages/GeneratorPage';

test.describe('LinkedIn Post Generator Flow', () => {
  let generatorPage: GeneratorPage;

  test.beforeEach(async ({ page }) => {
    generatorPage = new GeneratorPage(page);

    // Capture console logs to debug frontend/SSE issues
    page.on('console', msg => console.log(`[Browser Console]: ${msg.text()}`));

    await generatorPage.goto();

    // Bypass frontend login overlay for E2E tests
    await page.evaluate(() => {
      const loginOverlay = document.getElementById('login-overlay');
      const mainApp = document.getElementById('main-app');
      if (loginOverlay) loginOverlay.style.display = 'none';
      if (mainApp) mainApp.style.display = 'grid';
      window.appUserId = 'default';
    });

    // Wait for the app to be visible
    await page.locator('#main-app').waitFor({ state: 'visible' });
  });

  test('should generate post with Auto-Topic', async ({ page }) => {
    test.setTimeout(180000);

    // 1. Enable Auto Topic
    await generatorPage.toggleAutoTopic();
    await expect(page.locator('#auto-topic-hint')).toBeVisible();

    // 2. Enable Lead Magnet
    await generatorPage.toggleLeadMagnet();

    // 3. Initiate Generation
    await generatorPage.generate();

    // Wait for the Auto-Topic SSE event
    await expect(generatorPage.topicInput).not.toHaveValue('', { timeout: 60000 });
    const autoGeneratedTopic = await generatorPage.topicInput.inputValue();
    console.log(`Auto-generated topic: ${autoGeneratedTopic}`);
    expect(autoGeneratedTopic.length).toBeGreaterThan(5);

    // 4. Wait for full generation to complete and verify caption has content
    // We increase timeout to 120s as some complex generations take over 90s
    await expect(generatorPage.captionPreview).not.toBeEmpty({ timeout: 120000 });

    // Check if the generate button is re-enabled, indicating the full sequence finished
    await expect(generatorPage.generateBtn).toBeEnabled({ timeout: 10000 });

    const outputText = await generatorPage.captionPreview.innerText();
    expect(outputText.length).toBeGreaterThan(50);
    console.log('Post generated successfully!');

    // 5. Conditionally check lead magnets
    const isLeadMagnetVisible = await generatorPage.leadMagnetsContainer.isVisible();
    if (isLeadMagnetVisible) {
      const leadMagnetItemsCount = await generatorPage.leadMagnetsList.locator('li').count();
      console.log(`Found ${leadMagnetItemsCount} lead magnets.`);
      expect(leadMagnetItemsCount).toBeGreaterThan(0);
    } else {
      console.log('LLM decided not to include a lead magnet for this specific topic.');
    }

    await page.screenshot({ path: 'playwright-report/successful-generation.png', fullPage: true });
  });
});
